# Generated by Django 3.1.4 on 2020-12-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='number',
        ),
    ]
